#!/bin/bash
# Time Capsule Proxy for SmallMediaHub - Updates and readme on https://github.com/leobrigassi/time-capsule-proxy
TCPROXY_VERSION=v2.0.0_beta1.0
TCPROXY_BRANCH=v2.0.0

current_dir=$(pwd | awk -F'/' '{print $NF}')
if [ $current_dir == "tcproxy" ]; then
    echo "[  ] Extracting in tcproxy/ directory..."
else
    echo "[  ] Creating and extracting in tcproxy/ directory..."
    mkdir -p tcproxy &&
    cd tcproxy >/dev/null 2>&1
fi

downloadTC() {
wget https://github.com/leobrigassi/Time_Capsule_Proxy/archive/refs/heads/$TCPROXY_BRANCH.tar.gz &&
tar -xzf $TCPROXY_BRANCH.tar.gz --strip-components=1 && rm $TCPROXY_BRANCH.tar.gz &&
chmod +x tcproxy
}

downloadTC >/dev/null 2>&1